version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: database
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - redis
      - localstack
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A src.documents.tasks worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - ./src:/app/src

volumes:
  postgres_data: